import React, { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

// import { listProducts } from ".../api";
// import useGlobalFetch from ".../hooks/useGlobalFetch";

export default function Home() {
  // const { data, isLoading, isError } = useGlobalFetch(
  //   `/products`,
  //   listProducts
  // );

  // console.log(data, "---<<<------");

  return (
    <div>
      <Head>
        <title>Product Detail</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='m-8 lg:m-16 lg:ml-60 lg:mr-60'>
        <div className=''>
          <div className='flex'>
            <img src='https://via.placeholder.com/250x350'></img>
            <div className='pl-12 flex flex-col'>
              <h1 className='text-3xl font-bold pb-8'>Apple iphone 12s</h1>
              <span className='text-2xl lg:text-3xl   text-gray-900 dark:text-white'>
                $599
              </span>
            </div>
          </div>
          <hr className='mt-12 mb-12'></hr>
          <h2 className='text-3xl font-bold mb-12'>Description</h2>
          <p>Some text</p>
        </div>
      </main>
    </div>
  );
}
