import React, { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useForm, SubmitHandler } from "react-hook-form";

import { listProducts } from "../api";
import useGlobalFetch from "../hooks/useGlobalFetch";
import Dropdown from "../components/Dropdown";

export default function AddProduct() {
  const [dropdownOpen, setDropdownOpen] = useState(false);
  const [selectedTag, setSelectedTag] = useState("");

  const { register, handleSubmit, reset } = useForm();

  const onSubmit = async (formData) => {
    if (formData) {
      const productData = { ...formData, category: selectedTag };
      console.log(productData, "====");
      reset();
      setSelectedTag("");
      try {
        //    await resendVerificationEmail(formData.username);
      } catch (err) {
        console.log(err);
      }
    }
  };

  return (
    <div>
      <Head>
        <title>Add Product</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='m-8 lg:m-16 grid place-content-center place-items-center'>
        <h1 className='text-4xl'>Create Product</h1>
        <div className='m-5 mt-20' style={{ width: "350px" }}>
          <div className='w-full'>
            <form
              className='bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 w-full'
              onSubmit={handleSubmit(onSubmit)}
            >
              <div className='mb-4'>
                <label className='block text-gray-700 text-sm font-bold mb-2'>
                  Product Name
                </label>
                <input
                  className='inputStyling'
                  type='text'
                  placeholder='Product Name'
                  {...register("productName")}
                ></input>
              </div>
              <div className='mb-4'>
                <label className='block mb-2 text-sm font-medium text-gray-900 dark:text-gray-400'>
                  Description
                </label>
                <textarea
                  id='message'
                  rows='4'
                  className='inputStyling'
                  placeholder='Description'
                  {...register("description")}
                ></textarea>
              </div>
              <div className='mb-4'>
                <label className='block text-gray-700 text-sm font-bold mb-2'>
                  Image Url
                </label>
                <input
                  className='inputStyling'
                  type='text'
                  placeholder='Image url'
                  {...register("imageUrl")}
                ></input>
              </div>
              <div className='mb-4'>
                <label className='block text-gray-700 text-sm font-bold mb-2'>
                  Categories
                </label>
                <Dropdown
                  dropdownOpen={dropdownOpen}
                  setDropdownOpen={setDropdownOpen}
                  selectedTag={selectedTag}
                  setSelectedTag={setSelectedTag}
                  fullWidth
                />
              </div>
              <div className='mb-4'>
                <label className='block text-gray-700 text-sm font-bold mb-2'>
                  Price
                </label>
                <input
                  className='inputStyling'
                  type='number'
                  placeholder='Price'
                  {...register("price")}
                ></input>
              </div>
              <button
                className='bg-slate-700 hover:bg-slate-800 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-full'
                type='submit'
              >
                Submit
              </button>
            </form>
          </div>
        </div>
      </main>
    </div>
  );
}
