import React, { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { listProducts } from "../api";
import useGlobalFetch from "../hooks/useGlobalFetch";

export default function Home() {
  const { data, isLoading, isError } = useGlobalFetch(
    `/products`,
    listProducts
  );

  console.log(data, "---<<<------");

  return (
    <div className={styles.container}>
      <Head>
        <title></title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <div className='text-2xl text-blue-600'>Hello world!</div>
      </main>
    </div>
  );
}
