import React, { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { listProducts } from "../api";
import useGlobalFetch from "../hooks/useGlobalFetch";
import useInput from "../hooks/useInput";
import Dropdown from "../components/Dropdown";
import ProductCard from "../components/ProductCard";

export default function Home() {
  const { inputValue, handleInput, clearInput } = useInput();
  const [dropdownOpen, setDropdownOpen] = useState(false);
  const [selectedTag, setSelectedTag] = useState("");
  // const { data, isLoading, isError } = useGlobalFetch(
  //   `/products`,
  //   listProducts
  // );

  // console.log(data, "---<<<------");

  console.log(inputValue);

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='m-8 lg:m-16'>
        <div className='p-8 bg-white shadow-lg rounded-md text-2xl text-center'>
          UPayments Store
        </div>
        <div className='flex justify-between mt-10'>
          <input
            className='shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline w-36 md:w-72 lg:w-72'
            id='search'
            type='text'
            placeholder='Search products'
            onChange={handleInput}
          ></input>
          <Dropdown
            dropdownOpen={dropdownOpen}
            setDropdownOpen={setDropdownOpen}
            selectedTag={selectedTag}
            setSelectedTag={setSelectedTag}
          />
        </div>
        <div className='grid grid-cols-2 gap-3 lg:grid-cols-4 lg:gap-4 md:grid-cols-3 mt-28 max-w-10xl lg:ml-20 lg:mr-20'>
          <ProductCard />
          <ProductCard />
          <ProductCard />
          <ProductCard />
          <ProductCard />
          <ProductCard />
          <ProductCard />
        </div>
      </main>
    </div>
  );
}
