import React, { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

import { listProducts, listCategories } from "../api";
import useGlobalFetch from "../hooks/useGlobalFetch";
import useInput from "../hooks/useInput";
import Dropdown from "../components/Dropdown";
import ProductCard from "../components/ProductCard";

export default function Home() {
  const { inputValue, handleInput, clearInput } = useInput();
  const [dropdownOpen, setDropdownOpen] = useState(false);
  const [selectedTag, setSelectedTag] = useState("");
  const { data, isLoading, isError } = useGlobalFetch(
    `/products`,
    listProducts
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='m-8 lg:m-16'>
        <Link href='/add-product'>
          <a>
            <button className=' hover:bg-slate-800 text-white font-bold py-2 px-4 rounded-full fixed bottom-20 right-20 bg-slate-600 shadow-2xl'>
              Add Product
            </button>
          </a>
        </Link>
        <div className='flex justify-between mt-10'>
          <input
            className='shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline w-36 md:w-72 lg:w-72'
            id='search'
            type='text'
            placeholder='Search products'
            onChange={handleInput}
          ></input>
          <Dropdown
            dropdownOpen={dropdownOpen}
            setDropdownOpen={setDropdownOpen}
            selectedTag={selectedTag}
            setSelectedTag={setSelectedTag}
          />
        </div>
        {isLoading ? (
          <div className='text-3xl text-center grid place-content-center'>
            Loading...
          </div>
        ) : null}
        {!isLoading && (
          <div className='grid grid-cols-2 gap-3 lg:grid-cols-4 lg:gap-4 md:grid-cols-3 mt-28 max-w-10xl lg:ml-20 lg:mr-20'>
            {data?.products?.map((product) => {
              const { avatar, name, price, _id } = product;
              return (
                <ProductCard
                  key={_id}
                  avatar={avatar}
                  name={name}
                  price={price}
                  id={_id}
                />
              );
            })}
          </div>
        )}
      </main>
    </div>
  );
}
